<?php
class SessionHandler implements SessionHandlerInterface, SessionUpdateTimestampHandlerInterface {
    public function close(){
        return true;
    }
    public function destroy($sessionId){
        return true;
    }
    public function gc($maximumLifetime){
        return true;
    }
    public function open($sessionSavePath, $sessionName){
        return true;
    }
    public function read($sessionId){
        // return value should be the session data or an empty string
        // ...
    }
    public function write($sessionId, $sessionData){
        // return value should be true for success or false for failure
        // ...
    }
    public function create_sid(){
        // available since PHP 5.5.1
        // invoked internally when a new session id is needed
        // no parameter is needed and return value should be the new session id created
        // ...
    }
    public function validateId($sessionId){
        // implements SessionUpdateTimestampHandlerInterface::validateId()
        // available since PHP 7.0
        // return value should be true if the session id is valid otherwise false
        // if false is returned a new session id will be generated by php internally
        // ...
    }
    public function updateTimestamp($sessionId, $sessionData){
        return true;
    }
}
